# branches:
#   only:
#   - master
dist: trusty
language: ocaml
sudo: required

before_install:
- sh travis-scripts/prepare-trusty.sh

install:
- sh travis-scripts/prepare-opam.sh

script:
- export OPAMYES=1
- opam sw 4.05.0
- eval `opam config env`
- make tezos
- make

# TODO > add tests after make
# TODO > how to compile and test with tezos ?
