# branches:
#   only:
#   - master
dist: xenial
language: generic
sudo: required

cache:
  timeout: 1000
  directories:
  - $HOME/.opam
  - tezos

before_install:
- sh travis-scripts/prepare-ubuntu.sh

install:
- export OPAMYES=1
- sh travis-scripts/prepare-opam.sh
- bash travis-scripts/build-tezos.sh
- source travis-scripts/start-tezos-sandbox.sh

script:
- eval `opam config env`
- make
- make tests-mini
- make tests
- make rev-tests

after_script:
- bash travis-scripts/stop-tezos-sandbox.sh
